### ISSUE TITLE
rust

### ISSUE THREAD

**Issue by ddkwork** [Zero-Tang/NoirVisor#33]
rust已被Windows支持，微软发布了一个名为Windows driver rs
的库

https://github.com/microsoft/windows-drivers-rs

**Comment by Zero-Tang** [comment]
> Hello,
> 
> While researching various hypervisors for a project although while coming from a C/C++ background, I and eager to jump into Rust since it seems to have some great features.
> 
> I just came across NoirVisor and am wondering if there has been any progress on the Rust port.
> 
> Thanks in advance and have a great day

In short, no progress on Rust whatsoever so far, even though I understand the great advantage of Rust. I'm sorry I made you hear this.

**Comment by lonnietc** [comment]
Thanks for the quick up on this, my friend.

Actually, I too have not yet jumped heavily into Rust but it was just an idea since technically having a C/C++ hypervisor would work as well.

What I am looking for is a type of "BluePill" Type-2 hypervisor that can be loaded and started from different OS's (mostly Windows and Linux) and installed as a driver perhaps, or maybe later as and EFI on boot.

In general, the idea is to build a type of OS agnostic Hypervisor Routing Mesh VPN that will intercept packets at the L2 data-link layer and then  pass through the packets that are for the virtualized OS (i.e. Windows 10) if that is the destination, or forward them to neighbors to send it on its way.  Effectively building a Hypervisor Switch that runs at Ring-0 with the OS virtualized. This should make the virtual switch more secure, faster, and able to be transparent to the OS once turned on at the OS layer.

Of course, there is much more to this project idea, but it is to effectively build out a new type of Hypervisor P2P switch that is abstracted away from the OS.

I think that your NoirVisor has some interesting possibilities towards this goal.

Maybe we can discuss it more if you are interested.

Thanks and have a great day

**Comment by lonnietc** [comment]
Thanks and we can close this now.

**Comment by Zero-Tang** [comment]
As of the sixth anniversary of NoirVisor, I am adopting the Rust programming language to this project. A [new `rust-dev` branch](https://github.com/Zero-Tang/NoirVisor/tree/rust-dev) has been created. This branch will not aggressively retire all legacy C codes, only the core of NoirVisor will be refactored. It will be merged into the `master` branch after all existing core features (system subversion and customizable virtual machines) are implemented in Rust. Once merged, the retired C codes will be moved to the archive branch.

I am closing this issue. Reopen this issue if there are further questions.
